name: Compatibility Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [published]

  workflow_dispatch:
jobs:
  test:
    name: Run tests on NCM ${{matrix.ncm-downloads}}
    runs-on: windows-latest
    strategy:
      max-parallel: 4
      matrix:
        ncm-downloads: 
              - 2.10.6.200601
              - 2.10.5.200451
              - 2.10.4.200380
              - 2.10.2.200154
    steps:
      - uses: actions/checkout@v3
      - name: Install NCM ${{matrix.ncm-downloads}} and BetterNCM
        shell: pwsh
        run:
            mkdir C:\users\runneradmin\betterncm\plugins_dev;
            cp ./ "C:\users\runneradmin\betterncm\plugins_dev" -recurse -Force;
            Invoke-WebRequest "https://d1.music.126.net/dmusic/NeteaseCloudMusic_Music_official_${{matrix.ncm-downloads}}.exe" -OutFile CloudMusic_Installer.exe;
            .\CloudMusic_Installer.exe /S;
            while (!(Test-Path "C:\Program Files (x86)\NetEase\CloudMusic\cloudmusic.exe")) { Start-Sleep 10 };
            Invoke-WebRequest https://github.com/MicroCBer/BetterNCM/releases/download/0.2.5/BetterNCMII.dll -OutFile betterncm.dll;
            cp ./betterncm.dll "C:\Program Files (x86)\NetEase\CloudMusic\msimg32.dll" -Force;
            start "C:\Program Files (x86)\NetEase\CloudMusic\cloudmusic.exe";
      - name: Check if NCM Crashes
        shell: pwsh
        run:
          Start-Sleep 20;
          Get-Process cloudmusic;
  
      - uses: OrbitalOwen/desktop-screenshot-action@0.1
        name: take screenshot
        with:
          file-name: 'desktop.jpg'
